# -*- coding: utf-8 -*-
"""cart-genie-final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oxtDQvFa029ncac_DTd9pQJUSp-msR4U
"""

!pip install pyngrok ngrok requests pillow sentence-transformers transformers

import os
from http.server import HTTPServer, BaseHTTPRequestHandler
from pyngrok import ngrok
import json
import requests
from io import BytesIO
from sentence_transformers import SentenceTransformer
from PIL import Image

model = SentenceTransformer('clip-ViT-B-32')

def get_image_embedding_from_url(url):
    response = requests.get(url)
    response.raise_for_status()
    image = Image.open(BytesIO(response.content)).convert("RGB")
    embedding = model.encode(image)
    return json.dumps(embedding.tolist())

ngrok.set_auth_token(os.environ["NGROK_AUTHTOKEN"])

class SimpleHandler(BaseHTTPRequestHandler):
    def do_POST(self):
        if self.path == "/getembeds":
            content_length = int(self.headers['Content-Length'])
            post_data = self.rfile.read(content_length)
            data = json.loads(post_data.decode('utf-8'))


            self.send_response(200)
            self.send_header("Content-type", "application/json")
            self.end_headers()
            response = json.dumps({"status": "received", "embeddings": get_image_embedding_from_url(data["url"])})
            self.wfile.write(response.encode('utf-8'))

# Open ngrok tunnel
public_url = ngrok.connect(os.environ["NGROK_PORT"])
print("Ngrok tunnel URL:", public_url)

# Start server
httpd = HTTPServer(('localhost', os.environ["NGROK_PORT"]), SimpleHandler)
print(f"Serving on port {os.environ["NGROK_PORT"]}")
httpd.serve_forever()
