# # -*- coding: utf-8 -*-
# """scrape.ipynb
#
# Automatically generated by Colab.
# """

# !pip install sentence-transformers pillow transformers flask-restful pyngrok

import requests
from io import BytesIO
from pyngrok import ngrok
from sentence_transformers import SentenceTransformer
from PIL import Image
from transformers import logging
from flask import Flask, request, jsonify
from google.colab import userdata
logging.set_verbosity_error()

model = SentenceTransformer('clip-ViT-B-32')

ngrok.set_auth_token(userdata.get('NGROK_AUTHTOKEN'))

app = Flask(__name__)

def get_image_embedding_from_url(url):
    response = requests.get(url)
    response.raise_for_status()
    image = Image.open(BytesIO(response.content)).convert("RGB")
    embedding = model.encode(image)
    return embedding.tolist()


@app.route("/upload", methods = ["POST"])
def upload():
  return jsonify(get_image_embedding_from_url(request.json["url"])), 200


if __name__ == "__main__":
  public_url = ngrok.connect(5000)
  print("Ngrok tunnel URL:", public_url)
  app.run(host='0.0.0.0' , port=5000, debug = False)

#
# from sentence_transformers import SentenceTransformer
# from transformers import logging
#
# logging.set_verbosity_error()
#
# model = SentenceTransformer('clip-ViT-B-32')
#
#
#
# if __name__ == "__main__":
#   text = "Men's shirts and tshirts"
#   print(json.dumps(model.encode(text).tolist()))
